---
- name: create mysql instances on k8s-db1
  hosts: [dbtest]
  vars_files:
    - vars.yaml

  tasks:
    - shell: "cat /etc/mysql/instances_root_pass"
      register: cat_mysql_root_pass

    - set_fact: mysql_root_pass="{{ cat_mysql_root_pass.stdout }}"
    - debug: msg="{{ mysql_root_pass }}"
