---
- name: mysql instance init
  hosts: [db1]
  vars_files:
    - vars.yaml
  tasks:
    - shell: "cat /etc/mysql/instances_root_pass"
      register: cat_mysql_root_pass

    - set_fact: mysql_root_pass="{{ cat_mysql_root_pass.stdout }}"
    - debug: msg="mysql root pass is {{mysql_root_pass}}"

    - name: get instance 1 master status
      mysql_replication:
        login_host: "{{ mysql_host1 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: getmaster
      register: mysql1_master_status
      
    - name: show mysql1 master status
      debug:
        msg: "{{ mysql1_master_status }}"

    - name: mysql2 stop slave
      mysql_replication:
        login_host: "{{ mysql_host2 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: stopslave

    - name: set instance2 slave
      mysql_replication:
        login_host: "{{ mysql_host2 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: changemaster
        master_host: "{{ mysql_host1 }}"
        master_port: "{{ mysql_port }}"
        master_user: "replication"
        master_password: "{{ mysql_new_user_pass }}"
        master_log_file: "{{ mysql1_master_status.File }}"
        master_log_pos: "{{ mysql1_master_status.Position }}"

    - name: mysql2 start slave
      mysql_replication:
        login_host: "{{ mysql_host2 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: startslave


    - name: get instance 2  master status
      mysql_replication:
        login_host: "{{ mysql_host2 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: getmaster
      register: mysql2_master_status

    - name: show mysql2 master status
      debug:
        msg: "{{ mysql2_master_status }}"

    - name: mysql1 stop slave
      mysql_replication:
        login_host: "{{ mysql_host1 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: stopslave


    - name: set instance1 slave
      mysql_replication:
        login_host: "{{ mysql_host1 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: changemaster
        master_host: "{{ mysql_host2 }}"
        master_port: "{{ mysql_port }}"
        master_user: "replication"
        master_password: "{{ mysql_new_user_pass }}"
        master_log_file: "{{ mysql2_master_status.File }}"
        master_log_pos: "{{ mysql2_master_status.Position }}"

    - name: mysql1 start slave
      mysql_replication:
        login_host: "{{ mysql_host1 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: startslave

    - name: get instance 1 slave status
      mysql_replication:
        login_host: "{{ mysql_host1 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: getslave
      register: mysql1_slave_status

    - name: get instance 2 slave status
      mysql_replication:
        login_host: "{{ mysql_host2 }}"
        login_port: "{{ mysql_port }}"
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        mode: getslave
      register: mysql2_slave_status

    - name: show mysql1 slave status
      debug:
        msg: "{{ mysql1_slave_status }}"

    - name: show mysql2 slave status
      debug:
        msg: "{{ mysql2_slave_status }}"
      
